In [1]:
%pip install -r requirements.txt

Requirement already satisfied: anaconda-anon-usage==0.8.1 in /home/bi23014_itu/miniconda3/lib/python3.14/site-packages (from -r requirements.txt (line 1)) (0.8.1)
Requirement already satisfied: anaconda-auth==0.15.1 in /home/bi23014_itu/miniconda3/lib/python3.14/site-packages (from -r requirements.txt (line 2)) (0.15.1)
Requirement already satisfied: anaconda-channel-guide==0.1.1 in /home/bi23014_itu/miniconda3/lib/python3.14/site-packages (from -r requirements.txt (line 3)) (0.1.1)
Requirement already satisfied: anaconda-cli-base==0.9.1 in /home/bi23014_itu/miniconda3/lib/python3.14/site-packages (from -r requirements.txt (line 4)) (0.9.1)
Requirement already satisfied: annotated-doc==0.0.4 in /home/bi23014_itu/miniconda3/lib/python3.14/site-packages (from -r requirements.txt (line 5)) (0.0.4)
Requirement already satisfied: annotated-types==0.6.0 in /home/bi23014_itu/miniconda3/lib/python3.14/site-packages (from -r requirements.txt (line 6)) (0.6.0)
Requirement already satisfied: anyio==4.12.1 in /home/bi23014_itu/miniconda3/lib/python3.14/site-packages (from -r requirements.txt (line 7)) (4.12.1)
Requirement already satisfied: archspec==0.2.6 in /home/bi23014_itu/miniconda3/lib/python3.14/site-packages (from -r requirements.txt (line 8)) (0.2.6)
Requirement already satisfied: asttokens==3.0.2 in /home/bi23014_itu/miniconda3/lib/python3.14/site-packages (from -r requirements.txt (line 9)) (3.0.2)
Requirement already satisfied: boltons==25.0.0 in /home/bi23014_itu/miniconda3/lib/python3.14/site-packages (from -r requirements.txt (line 10)) (25.0.0)
Requirement already satisfied: brotlicffi==1.2.0.0 in /home/bi23014_itu/miniconda3/lib/python3.14/site-packages (from -r requirements.txt (line 11)) (1.2.0.0)
Requirement already satisfied: build==1.3.0 in /home/bi23014_itu/miniconda3/lib/python3.14/site-packages (from -r requirements.txt (line 12)) (1.3.0)
Requirement already satisfied: certifi==2026.7.22 in /home/bi23014_itu/miniconda3/lib/python3.14/site-packages (from -r requirements.txt (line 13)) (2026.7.22)
Requirement already satisfied: cffi==2.0.0 in /home/bi23014_itu/miniconda3/lib/python3.14/site-packages (from -r requirements.txt (line 14)) (2.0.0)
Requirement already satisfied: charset-normalizer==3.4.7 in /home/bi23014_itu/miniconda3/lib/python3.14/site-packages (from -r requirements.txt (line 15)) (3.4.7)
Requirement already satisfied: click==8.4.1 in /home/bi23014_itu/miniconda3/lib/python3.14/site-packages (from -r requirements.txt (line 16)) (8.4.1)
Requirement already satisfied: comm==0.2.3 in /home/bi23014_itu/miniconda3/lib/python3.14/site-packages (from -r requirements.txt (line 17)) (0.2.3)
Requirement already satisfied: conda==26.7.2 in /home/bi23014_itu/miniconda3/lib/python3.14/site-packages (from -r requirements.txt (line 18)) (26.7.2)
Requirement already satisfied: conda-anaconda-telemetry==0.3.0 in /home/bi23014_itu/miniconda3/lib/python3.14/site-packages (from -r requirements.txt (line 19)) (0.3.0)
Requirement already satisfied: conda-anaconda-tos==0.2.2 in /home/bi23014_itu/miniconda3/lib/python3.14/site-packages (from -r requirements.txt (line 20)) (0.2.2)
Requirement already satisfied: conda-content-trust==0.3.2 in /home/bi23014_itu/miniconda3/lib/python3.14/site-packages (from -r requirements.txt (line 21)) (0.3.2)
Requirement already satisfied: conda_index==0.12.1 in /home/bi23014_itu/miniconda3/lib/python3.14/site-packages (from -r requirements.txt (line 22)) (0.12.1)
Requirement already satisfied: conda-libmamba-solver==26.6.0 in /home/bi23014_itu/miniconda3/lib/python3.14/site-packages (from -r requirements.txt (line 23)) (26.6.0)
Requirement already satisfied: conda-lockfiles==0.2.0 in /home/bi23014_itu/miniconda3/lib/python3.14/site-packages (from -r requirements.txt (line 24)) (0.2.0)
Requirement already satisfied: conda-package-handling==2.5.0 in /home/bi23014_itu/miniconda3/lib/python3.14/site-packages (from -r requirements.txt (line 25)) (2.5.0)
Requirement already satisfied: conda_package_streaming==0.13.0 in /home/bi23014_itu/miniconda3/lib/python3.14/site-packages (from -r requirements.txt (line 26)) (0.13.0)
Requirement already satisfied: conda-pypi==0.11.0 in /home/bi23014_itu/miniconda3/lib/python3.14/site-packages (from -r requirements.txt (line 27)) (0.11.0)
Requirement already satisfied: conda-rattler-solver==0.1.1 in /home/bi23014_itu/miniconda3/lib/python3.14/site-packages (from -r requirements.txt (line 28)) (0.1.1)
Requirement already satisfied: conda-self==0.2.0 in /home/bi23014_itu/miniconda3/lib/python3.14/site-packages (from -r requirements.txt (line 29)) (0.2.0)
Requirement already satisfied: contourpy==1.4.0 in /home/bi23014_itu/miniconda3/lib/python3.14/site-packages (from -r requirements.txt (line 30)) (1.4.0)
Requirement already satisfied: cryptography==49.0.0 in /home/bi23014_itu/miniconda3/lib/python3.14/site-packages (from -r requirements.txt (line 31)) (49.0.0)
Requirement already satisfied: cycler==0.12.1 in /home/bi23014_itu/miniconda3/lib/python3.14/site-packages (from -r requirements.txt (line 32)) (0.12.1)
Requirement already satisfied: debugpy==1.8.21 in /home/bi23014_itu/miniconda3/lib/python3.14/site-packages (from -r requirements.txt (line 33)) (1.8.21)
Requirement already satisfied: distro==1.9.0 in /home/bi23014_itu/miniconda3/lib/python3.14/site-packages (from -r requirements.txt (line 34)) (1.9.0)
Requirement already satisfied: executing==2.2.1 in /home/bi23014_itu/miniconda3/lib/python3.14/site-packages (from -r requirements.txt (line 35)) (2.2.1)
Requirement already satisfied: filelock==3.29.4 in /home/bi23014_itu/miniconda3/lib/python3.14/site-packages (from -r requirements.txt (line 36)) (3.29.4)
Requirement already satisfied: fonttools==4.65.0 in /home/bi23014_itu/miniconda3/lib/python3.14/site-packages (from -r requirements.txt (line 37)) (4.65.0)
Requirement already satisfied: frozendict==2.4.7 in /home/bi23014_itu/miniconda3/lib/python3.14/site-packages (from -r requirements.txt (line 38)) (2.4.7)
Requirement already satisfied: h11==0.16.0 in /home/bi23014_itu/miniconda3/lib/python3.14/site-packages (from -r requirements.txt (line 39)) (0.16.0)
Requirement already satisfied: httpcore==1.0.9 in /home/bi23014_itu/miniconda3/lib/python3.14/site-packages (from -r requirements.txt (line 40)) (1.0.9)
Requirement already satisfied: httpx==0.28.1 in /home/bi23014_itu/miniconda3/lib/python3.14/site-packages (from -r requirements.txt (line 41)) (0.28.1)
Requirement already satisfied: idna==3.18 in /home/bi23014_itu/miniconda3/lib/python3.14/site-packages (from -r requirements.txt (line 42)) (3.18)
Requirement already satisfied: installer==1.0.0 in /home/bi23014_itu/miniconda3/lib/python3.14/site-packages (from -r requirements.txt (line 43)) (1.0.0)
Requirement already satisfied: ipykernel==7.3.0 in /home/bi23014_itu/miniconda3/lib/python3.14/site-packages (from -r requirements.txt (line 44)) (7.3.0)
Requirement already satisfied: ipython==9.17.1 in /home/bi23014_itu/miniconda3/lib/python3.14/site-packages (from -r requirements.txt (line 45)) (9.17.1)
Requirement already satisfied: ipython_pygments_lexers==1.1.1 in /home/bi23014_itu/miniconda3/lib/python3.14/site-packages (from -r requirements.txt (line 46)) (1.1.1)
Requirement already satisfied: jaraco.classes==3.4.0 in /home/bi23014_itu/miniconda3/lib/python3.14/site-packages (from -r requirements.txt (line 47)) (3.4.0)
Requirement already satisfied: jaraco.context==6.1.0 in /home/bi23014_itu/miniconda3/lib/python3.14/site-packages (from -r requirements.txt (line 48)) (6.1.0)
Requirement already satisfied: jaraco.functools==4.4.0 in /home/bi23014_itu/miniconda3/lib/python3.14/site-packages (from -r requirements.txt (line 49)) (4.4.0)
Requirement already satisfied: jedi==0.20.0 in /home/bi23014_itu/miniconda3/lib/python3.14/site-packages (from -r requirements.txt (line 50)) (0.20.0)
Requirement already satisfied: jeepney==0.7.1 in /home/bi23014_itu/miniconda3/lib/python3.14/site-packages (from -r requirements.txt (line 51)) (0.7.1)
Requirement already satisfied: Jinja2==3.1.6 in /home/bi23014_itu/miniconda3/lib/python3.14/site-packages (from -r requirements.txt (line 52)) (3.1.6)
Requirement already satisfied: jsonpatch==1.33 in /home/bi23014_itu/miniconda3/lib/python3.14/site-packages (from -r requirements.txt (line 53)) (1.33)
Requirement already satisfied: jsonpointer==3.1.1 in /home/bi23014_itu/miniconda3/lib/python3.14/site-packages (from -r requirements.txt (line 54)) (3.1.1)
Requirement already satisfied: jupyter_client==8.10.0 in /home/bi23014_itu/miniconda3/lib/python3.14/site-packages (from -r requirements.txt (line 55)) (8.10.0)
Requirement already satisfied: jupyter_core==5.9.1 in /home/bi23014_itu/miniconda3/lib/python3.14/site-packages (from -r requirements.txt (line 56)) (5.9.1)
Requirement already satisfied: keyring==25.7.0 in /home/bi23014_itu/miniconda3/lib/python3.14/site-packages (from -r requirements.txt (line 57)) (25.7.0)
Requirement already satisfied: kiwisolver==1.5.1 in /home/bi23014_itu/miniconda3/lib/python3.14/site-packages (from -r requirements.txt (line 58)) (1.5.1)
Requirement already satisfied: libmambapy==2.3.2 in /home/bi23014_itu/miniconda3/lib/python3.14/site-packages (from -r requirements.txt (line 59)) (2.3.2)
Requirement already satisfied: markdown-it-py==4.0.0 in /home/bi23014_itu/miniconda3/lib/python3.14/site-packages (from -r requirements.txt (line 60)) (4.0.0)
Requirement already satisfied: MarkupSafe==3.0.3 in /home/bi23014_itu/miniconda3/lib/python3.14/site-packages (from -r requirements.txt (line 61)) (3.0.3)
Requirement already satisfied: matplotlib==3.11.2 in /home/bi23014_itu/miniconda3/lib/python3.14/site-packages (from -r requirements.txt (line 62)) (3.11.2)
Requirement already satisfied: matplotlib-inline==0.2.2 in /home/bi23014_itu/miniconda3/lib/python3.14/site-packages (from -r requirements.txt (line 63)) (0.2.2)
Requirement already satisfied: mdurl==0.1.2 in /home/bi23014_itu/miniconda3/lib/python3.14/site-packages (from -r requirements.txt (line 64)) (0.1.2)
Requirement already satisfied: menuinst==2.5.1 in /home/bi23014_itu/miniconda3/lib/python3.14/site-packages (from -r requirements.txt (line 65)) (2.5.1)
Requirement already satisfied: more-itertools==11.0.2 in /home/bi23014_itu/miniconda3/lib/python3.14/site-packages (from -r requirements.txt (line 66)) (11.0.2)
Requirement already satisfied: msgpack==1.2.1 in /home/bi23014_itu/miniconda3/lib/python3.14/site-packages (from -r requirements.txt (line 67)) (1.2.1)
Requirement already satisfied: nest-asyncio2==1.7.2 in /home/bi23014_itu/miniconda3/lib/python3.14/site-packages (from -r requirements.txt (line 68)) (1.7.2)
Requirement already satisfied: numpy==2.5.3 in /home/bi23014_itu/miniconda3/lib/python3.14/site-packages (from -r requirements.txt (line 69)) (2.5.3)
Requirement already satisfied: packaging==26.0 in /home/bi23014_itu/miniconda3/lib/python3.14/site-packages (from -r requirements.txt (line 70)) (26.0)
Requirement already satisfied: pandas==3.0.5 in /home/bi23014_itu/miniconda3/lib/python3.14/site-packages (from -r requirements.txt (line 71)) (3.0.5)
Requirement already satisfied: parso==0.8.7 in /home/bi23014_itu/miniconda3/lib/python3.14/site-packages (from -r requirements.txt (line 72)) (0.8.7)
Requirement already satisfied: pathlib==1.0.1 in /home/bi23014_itu/miniconda3/lib/python3.14/site-packages (from -r requirements.txt (line 73)) (1.0.1)
Requirement already satisfied: pexpect==4.9.0 in /home/bi23014_itu/miniconda3/lib/python3.14/site-packages (from -r requirements.txt (line 74)) (4.9.0)
Requirement already satisfied: pillow==12.3.0 in /home/bi23014_itu/miniconda3/lib/python3.14/site-packages (from -r requirements.txt (line 75)) (12.3.0)
Requirement already satisfied: pip==26.1.2 in /home/bi23014_itu/miniconda3/lib/python3.14/site-packages (from -r requirements.txt (line 76)) (26.1.2)
Requirement already satisfied: pkce==1.0.3 in /home/bi23014_itu/miniconda3/lib/python3.14/site-packages (from -r requirements.txt (line 77)) (1.0.3)
Requirement already satisfied: platformdirs==4.9.4 in /home/bi23014_itu/miniconda3/lib/python3.14/site-packages (from -r requirements.txt (line 78)) (4.9.4)
Requirement already satisfied: pluggy==1.6.0 in /home/bi23014_itu/miniconda3/lib/python3.14/site-packages (from -r requirements.txt (line 79)) (1.6.0)
Requirement already satisfied: prompt_toolkit==3.0.53 in /home/bi23014_itu/miniconda3/lib/python3.14/site-packages (from -r requirements.txt (line 80)) (3.0.53)
Requirement already satisfied: psutil==7.2.2 in /home/bi23014_itu/miniconda3/lib/python3.14/site-packages (from -r requirements.txt (line 81)) (7.2.2)
Requirement already satisfied: ptyprocess==0.7.0 in /home/bi23014_itu/miniconda3/lib/python3.14/site-packages (from -r requirements.txt (line 82)) (0.7.0)
Requirement already satisfied: pure_eval==0.2.3 in /home/bi23014_itu/miniconda3/lib/python3.14/site-packages (from -r requirements.txt (line 83)) (0.2.3)
Requirement already satisfied: py-rattler==0.25.0 in /home/bi23014_itu/miniconda3/lib/python3.14/site-packages (from -r requirements.txt (line 84)) (0.25.0)
Requirement already satisfied: pycosat==0.6.6 in /home/bi23014_itu/miniconda3/lib/python3.14/site-packages (from -r requirements.txt (line 85)) (0.6.6)
Requirement already satisfied: pycparser==3.0 in /home/bi23014_itu/miniconda3/lib/python3.14/site-packages (from -r requirements.txt (line 86)) (3.0)
Requirement already satisfied: pydantic==2.13.4 in /home/bi23014_itu/miniconda3/lib/python3.14/site-packages (from -r requirements.txt (line 87)) (2.13.4)
Requirement already satisfied: pydantic_core==2.46.4 in /home/bi23014_itu/miniconda3/lib/python3.14/site-packages (from -r requirements.txt (line 88)) (2.46.4)
Requirement already satisfied: pydantic-settings==2.14.2 in /home/bi23014_itu/miniconda3/lib/python3.14/site-packages (from -r requirements.txt (line 89)) (2.14.2)
Requirement already satisfied: Pygments==2.20.0 in /home/bi23014_itu/miniconda3/lib/python3.14/site-packages (from -r requirements.txt (line 90)) (2.20.0)
Requirement already satisfied: PyJWT==2.13.0 in /home/bi23014_itu/miniconda3/lib/python3.14/site-packages (from -r requirements.txt (line 91)) (2.13.0)
Requirement already satisfied: pyparsing==3.3.2 in /home/bi23014_itu/miniconda3/lib/python3.14/site-packages (from -r requirements.txt (line 92)) (3.3.2)
Requirement already satisfied: pyproject_hooks==1.2.0 in /home/bi23014_itu/miniconda3/lib/python3.14/site-packages (from -r requirements.txt (line 93)) (1.2.0)
Requirement already satisfied: PySocks==1.7.1 in /home/bi23014_itu/miniconda3/lib/python3.14/site-packages (from -r requirements.txt (line 94)) (1.7.1)
Requirement already satisfied: python-dateutil==2.9.0.post0 in /home/bi23014_itu/miniconda3/lib/python3.14/site-packages (from -r requirements.txt (line 95)) (2.9.0.post0)
Requirement already satisfied: python-dotenv==1.2.1 in /home/bi23014_itu/miniconda3/lib/python3.14/site-packages (from -r requirements.txt (line 96)) (1.2.1)
Requirement already satisfied: pyzmq==27.2.0 in /home/bi23014_itu/miniconda3/lib/python3.14/site-packages (from -r requirements.txt (line 97)) (27.2.0)
Requirement already satisfied: readchar==4.2.2 in /home/bi23014_itu/miniconda3/lib/python3.14/site-packages (from -r requirements.txt (line 98)) (4.2.2)
Requirement already satisfied: requests==2.34.2 in /home/bi23014_itu/miniconda3/lib/python3.14/site-packages (from -r requirements.txt (line 99)) (2.34.2)
Requirement already satisfied: rich==15.0.0 in /home/bi23014_itu/miniconda3/lib/python3.14/site-packages (from -r requirements.txt (line 100)) (15.0.0)
Requirement already satisfied: ruamel.yaml==0.18.16 in /home/bi23014_itu/miniconda3/lib/python3.14/site-packages (from -r requirements.txt (line 101)) (0.18.16)
Requirement already satisfied: ruamel.yaml.clib==0.2.14 in /home/bi23014_itu/miniconda3/lib/python3.14/site-packages (from -r requirements.txt (line 102)) (0.2.14)
Requirement already satisfied: SecretStorage==3.5.0 in /home/bi23014_itu/miniconda3/lib/python3.14/site-packages (from -r requirements.txt (line 103)) (3.5.0)
Requirement already satisfied: semver==3.0.4 in /home/bi23014_itu/miniconda3/lib/python3.14/site-packages (from -r requirements.txt (line 104)) (3.0.4)
Requirement already satisfied: setuptools==82.0.1 in /home/bi23014_itu/miniconda3/lib/python3.14/site-packages (from -r requirements.txt (line 105)) (82.0.1)
Requirement already satisfied: shellingham==1.5.4 in /home/bi23014_itu/miniconda3/lib/python3.14/site-packages (from -r requirements.txt (line 106)) (1.5.4)
Requirement already satisfied: six==1.17.0 in /home/bi23014_itu/miniconda3/lib/python3.14/site-packages (from -r requirements.txt (line 107)) (1.17.0)
Requirement already satisfied: stack_data==0.6.3 in /home/bi23014_itu/miniconda3/lib/python3.14/site-packages (from -r requirements.txt (line 108)) (0.6.3)
Requirement already satisfied: tomli==2.4.0 in /home/bi23014_itu/miniconda3/lib/python3.14/site-packages (from -r requirements.txt (line 109)) (2.4.0)
Requirement already satisfied: tomli_w==1.2.0 in /home/bi23014_itu/miniconda3/lib/python3.14/site-packages (from -r requirements.txt (line 110)) (1.2.0)
Requirement already satisfied: tomlkit==0.13.3 in /home/bi23014_itu/miniconda3/lib/python3.14/site-packages (from -r requirements.txt (line 111)) (0.13.3)
Requirement already satisfied: tornado==6.5.8 in /home/bi23014_itu/miniconda3/lib/python3.14/site-packages (from -r requirements.txt (line 112)) (6.5.8)
Requirement already satisfied: tqdm==4.68.2 in /home/bi23014_itu/miniconda3/lib/python3.14/site-packages (from -r requirements.txt (line 113)) (4.68.2)
Requirement already satisfied: traitlets==5.16.1 in /home/bi23014_itu/miniconda3/lib/python3.14/site-packages (from -r requirements.txt (line 114)) (5.16.1)
Requirement already satisfied: truststore==0.10.4 in /home/bi23014_itu/miniconda3/lib/python3.14/site-packages (from -r requirements.txt (line 115)) (0.10.4)
Requirement already satisfied: typer==0.25.1 in /home/bi23014_itu/miniconda3/lib/python3.14/site-packages (from -r requirements.txt (line 116)) (0.25.1)
Requirement already satisfied: typing_extensions==4.15.0 in /home/bi23014_itu/miniconda3/lib/python3.14/site-packages (from -r requirements.txt (line 117)) (4.15.0)
Requirement already satisfied: typing-inspection==0.4.2 in /home/bi23014_itu/miniconda3/lib/python3.14/site-packages (from -r requirements.txt (line 118)) (0.4.2)
Requirement already satisfied: unearth==0.18.2 in /home/bi23014_itu/miniconda3/lib/python3.14/site-packages (from -r requirements.txt (line 119)) (0.18.2)
Requirement already satisfied: urllib3==2.7.0 in /home/bi23014_itu/miniconda3/lib/python3.14/site-packages (from -r requirements.txt (line 120)) (2.7.0)
Requirement already satisfied: wcwidth==0.8.3 in /home/bi23014_itu/miniconda3/lib/python3.14/site-packages (from -r requirements.txt (line 121)) (0.8.3)
Requirement already satisfied: wheel==0.47.0 in /home/bi23014_itu/miniconda3/lib/python3.14/site-packages (from -r requirements.txt (line 122)) (0.47.0)
Requirement already satisfied: zstandard==0.25.0 in /home/bi23014_itu/miniconda3/lib/python3.14/site-packages (from -r requirements.txt (line 123)) (0.25.0)
Note: you may need to restart the kernel to use updated packages.

In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

path = "../data/exp1_824.csv"
df = pd.read_csv(path)

In [2]:
df

,StartDate,EndDate,Status,IPAddress,Progress,Duration (in seconds),Finished,RecordedDate,ResponseId,RecipientLastName,...,5_Q1149_Page Submit,5_Q1149_Click Count,5_Q1150_1,5_Q1151_1,__js_DisplayedMessage,__js_MessageGroup,__js_MessageStatus,__js_MessageTimestamp,__js_MessageError,__js_MessageLogs
0,2026-08-22 09:31:58,2026-08-22 09:48:49,IP Address,126.72.104.33,100,1010,True,2026-08-22 09:48:50,R_9nvFNaU5rMNP8Vi,NaN,...,NaN,NaN,NaN,NaN,午後の作業に取りかかったよ,neutral,success,2026-08-22T00:48:30.677Z,NaN,"[{""displayedMessage"":""目を閉じてそのまま過ごしてたよ"",""messag..."
1,2026-08-22 09:35:38,2026-08-22 09:52:15,IP Address,219.104.142.133,100,995,True,2026-08-22 09:52:16,R_4l6l7Hlm3o0SkDf,NaN,...,NaN,NaN,NaN,NaN,明日の面接で質問にちゃんと答えられるか心配だ,negative,success,2026-08-22T00:51:48.610Z,NaN,"[{""displayedMessage"":""朝起きれない"",""messageGroup"":""..."
2,2026-08-22 09:34:57,2026-08-22 09:54:03,IP Address,121.92.154.87,100,1146,True,2026-08-22 09:54:04,R_41hDHe81EktidI7,NaN,...,NaN,NaN,NaN,NaN,外で変な音がした,negative,success,2026-08-22T00:53:18.126Z,NaN,"[{""displayedMessage"":""朝起きれない"",""messageGroup"":""..."
3,2026-08-22 09:35:05,2026-08-22 09:55:02,IP Address,220.153.182.43,100,1197,True,2026-08-22 09:55:03,R_4Gynm3Z3UbGjD7N,NaN,...,NaN,NaN,NaN,NaN,今日のトレーニングやり切って気持ち良い,positive,success,2026-08-22T00:54:49.078Z,NaN,"[{""displayedMessage"":""手伝ってくれたおかげで完成したよ"",""messa..."
4,2026-08-22 09:34:11,2026-08-22 09:57:15,IP Address,153.230.200.160,100,1384,True,2026-08-22 09:57:16,R_4Ycezp6tuSpxXkl,NaN,...,NaN,NaN,NaN,NaN,一日の流れだけ思い返したよ,neutral,success,2026-08-22T00:56:47.316Z,NaN,"[{""displayedMessage"":""少しだけ画面を見てたよ"",""messageGro..."
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
83,2026-08-22 11:41:31,2026-08-22 12:25:53,IP Address,211.15.31.227,100,2661,True,2026-08-22 12:25:54,R_98McUJwCYrrNLWw,NaN,...,NaN,NaN,NaN,NaN,自分だけ置いていかれているように感じる,negative,success,2026-08-22T03:24:35.605Z,NaN,"[{""displayedMessage"":""外で変な音がした"",""messageGroup""..."
84,2026-08-22 11:52:46,2026-08-22 12:31:38,IP Address,153.239.154.15,100,2332,True,2026-08-22 12:31:39,R_4f7jJrko3lRYwzK,NaN,...,NaN,NaN,NaN,NaN,昨日の会話で頭の中が真っ白になった,negative,success,2026-08-22T03:30:57.807Z,NaN,"[{""displayedMessage"":""こっちに向かって来る人がいる"",""message..."
85,2026-08-22 12:03:24,2026-08-22 12:32:13,IP Address,153.191.3.10,100,1729,True,2026-08-22 12:32:14,R_4Lb4PteTp7PpXc7,NaN,...,NaN,NaN,NaN,NaN,今日までの努力が報われたよ,positive,success,2026-08-22T03:31:35.719Z,NaN,"[{""displayedMessage"":""好きなことしてると幸せを感じる"",""messag..."
86,2026-08-22 12:08:38,2026-08-22 12:38:16,IP Address,210.130.62.242,100,1777,True,2026-08-22 12:38:16,R_9VvcEe2AaVFz2QF,NaN,...,NaN,NaN,NaN,NaN,お風呂の準備をしなきゃ,neutral,success,2026-08-22T03:37:43.823Z,NaN,"[{""displayedMessage"":""届いてた連絡を一通返しただけ"",""message..."
87,2026-08-22 12:47:33,2026-08-22 13:19:58,IP Address,210.139.197.228,100,1944,True,2026-08-22 13:19:59,R_48fjCyEBqTZJTy1,NaN,...,NaN,NaN,NaN,NaN,ごめん話を聞いてなかった,negative,success,2026-08-22T04:18:41.849Z,NaN,"[{""displayedMessage"":""楽しみにしていたライブが中止になった"",""mes..."

In [3]:
df.iloc[1,]

StartDate                                              2026-08-22 09:35:38
EndDate                                                2026-08-22 09:52:15
Status                                                          IP Address
IPAddress                                                  219.104.142.133
Progress                                                               100
                                               ...
__js_MessageGroup                                                 negative
__js_MessageStatus                                                 success
__js_MessageTimestamp                             2026-08-22T00:51:48.610Z
__js_MessageError                                                      NaN
__js_MessageLogs         [{"displayedMessage":"朝起きれない","messageGroup":"...
Name: 1, Length: 5232, dtype: object

In [4]:
ip_data = df["IPAddress"]

#重複IPの検知

ip_counts = df["IPAddress"].value_counts()

print(ip_counts[ip_counts > 1])

Series([], Name: count, dtype: int64)

In [5]:
# 削除したい列名
drop_cols = [
    "StartDate",
    "EndDate",
    "Status",
    "IPAddress",
    "Progress",
    "Duration (in seconds)",
    "Finished",
    "RecordedDate",
    "RecipientLastName",
    "RecipientFirstName",
    "RecipientEmail",
    "ExternalReference",
    "LocationLatitude",
    "LocationLongitude",
    "DistributionChannel",
    "UserLanguage",
    "最後に表示されたフロー要素ID",
    "最後に表示された質問ID",
    "D1",
    "D2_1",
    "B1"
]

# 不要列を削除してdfを更新
df = df.drop(columns=drop_cols)

print(df.shape)

(88, 5211)

In [6]:
drop_cols = df.columns[
    df.columns.astype(str).str.contains(
        "First Click|Last Click|Click Count|B2",
        na=False
    )
]

df = df.drop(columns=drop_cols)

In [7]:
# 全ての行がNaNの列を削除

data_body = df

# 全てNaNの列を判定
cols_to_drop = data_body.columns[data_body.isna().all()]

# 削除する列名を表示
print("削除する列数:", len(cols_to_drop))
print("削除する列名:")

for col in cols_to_drop:
    print(col)

# 列を削除a
df = data_body.drop(columns=cols_to_drop)

print("残った列数:", len(df.columns))
print("残った行数:", len(df))

削除する列数: 1501
削除する列名:
1_Q52_Page Submit
1_Q2_1
1_Q63_Page Submit
1_Q44_1.1
1_Q43_1
2_Q52_Page Submit
2_Q2_1
2_Q63_Page Submit
2_Q44_1.1
2_Q43_1
3_Q52_Page Submit
3_Q2_1
3_Q63_Page Submit
3_Q44_1.1
3_Q43_1
4_Q52_Page Submit
4_Q2_1
4_Q63_Page Submit
4_Q44_1.1
4_Q43_1
5_Q52_Page Submit
5_Q2_1
5_Q63_Page Submit
5_Q44_1.1
5_Q43_1
1_Q740_Page Submit
1_Q741_1
1_Q743_Page Submit
1_Q744_1
1_Q745_1
2_Q740_Page Submit
2_Q741_1
2_Q743_Page Submit
2_Q744_1
2_Q745_1
3_Q740_Page Submit
3_Q741_1
3_Q743_Page Submit
3_Q744_1
3_Q745_1
4_Q740_Page Submit
4_Q741_1
4_Q743_Page Submit
4_Q744_1
4_Q745_1
5_Q740_Page Submit
5_Q741_1
5_Q743_Page Submit
5_Q744_1
5_Q745_1
1_Q747_Page Submit
1_Q748_1
1_Q750_Page Submit
1_Q751_1
1_Q752_1
2_Q747_Page Submit
2_Q748_1
2_Q750_Page Submit
2_Q751_1
2_Q752_1
3_Q747_Page Submit
3_Q748_1
3_Q750_Page Submit
3_Q751_1
3_Q752_1
4_Q747_Page Submit
4_Q748_1
4_Q750_Page Submit
4_Q751_1
4_Q752_1
5_Q747_Page Submit
5_Q748_1
5_Q750_Page Submit
5_Q751_1
5_Q752_1
1_Q754_Page Submit
1_Q755_1
1_Q757_Page Submit
1_Q758_1
1_Q759_1
2_Q754_Page Submit
2_Q755_1
2_Q757_Page Submit
2_Q758_1
2_Q759_1
3_Q754_Page Submit
3_Q755_1
3_Q757_Page Submit
3_Q758_1
3_Q759_1
4_Q754_Page Submit
4_Q755_1
4_Q757_Page Submit
4_Q758_1
4_Q759_1
5_Q754_Page Submit
5_Q755_1
5_Q757_Page Submit
5_Q758_1
5_Q759_1
1_Q761_Page Submit
1_Q762_1
1_Q764_Page Submit
1_Q765_1
1_Q766_1
2_Q761_Page Submit
2_Q762_1
2_Q764_Page Submit
2_Q765_1
2_Q766_1
3_Q761_Page Submit
3_Q762_1
3_Q764_Page Submit
3_Q765_1
3_Q766_1
4_Q761_Page Submit
4_Q762_1
4_Q764_Page Submit
4_Q765_1
4_Q766_1
5_Q761_Page Submit
5_Q762_1
5_Q764_Page Submit
5_Q765_1
5_Q766_1
1_Q768_Page Submit
1_Q769_1
1_Q771_Page Submit
1_Q772_1
1_Q773_1
2_Q768_Page Submit
2_Q769_1
2_Q771_Page Submit
2_Q772_1
2_Q773_1
3_Q768_Page Submit
3_Q769_1
3_Q771_Page Submit
3_Q772_1
3_Q773_1
4_Q768_Page Submit
4_Q769_1
4_Q771_Page Submit
4_Q772_1
4_Q773_1
5_Q768_Page Submit
5_Q769_1
5_Q771_Page Submit
5_Q772_1
5_Q773_1
1_Q775_Page Submit
1_Q776_1
1_Q778_Page Submit
1_Q779_1
1_Q780_1
2_Q775_Page Submit
2_Q776_1
2_Q778_Page Submit
2_Q779_1
2_Q780_1
3_Q775_Page Submit
3_Q776_1
3_Q778_Page Submit
3_Q779_1
3_Q780_1
4_Q775_Page Submit
4_Q776_1
4_Q778_Page Submit
4_Q779_1
4_Q780_1
5_Q775_Page Submit
5_Q776_1
5_Q778_Page Submit
5_Q779_1
5_Q780_1
1_Q782_Page Submit
1_Q783_1
1_Q785_Page Submit
1_Q786_1
1_Q787_1
2_Q782_Page Submit
2_Q783_1
2_Q785_Page Submit
2_Q786_1
2_Q787_1
3_Q782_Page Submit
3_Q783_1
3_Q785_Page Submit
3_Q786_1
3_Q787_1
4_Q782_Page Submit
4_Q783_1
4_Q785_Page Submit
4_Q786_1
4_Q787_1
5_Q782_Page Submit
5_Q783_1
5_Q785_Page Submit
5_Q786_1
5_Q787_1
1_Q789_Page Submit
1_Q790_1
1_Q792_Page Submit
1_Q793_1
1_Q794_1
2_Q789_Page Submit
2_Q790_1
2_Q792_Page Submit
2_Q793_1
2_Q794_1
3_Q789_Page Submit
3_Q790_1
3_Q792_Page Submit
3_Q793_1
3_Q794_1
4_Q789_Page Submit
4_Q790_1
4_Q792_Page Submit
4_Q793_1
4_Q794_1
5_Q789_Page Submit
5_Q790_1
5_Q792_Page Submit
5_Q793_1
5_Q794_1
1_Q796_Page Submit
1_Q797_1
1_Q799_Page Submit
1_Q800_1
1_Q801_1
2_Q796_Page Submit
2_Q797_1
2_Q799_Page Submit
2_Q800_1
2_Q801_1
3_Q796_Page Submit
3_Q797_1
3_Q799_Page Submit
3_Q800_1
3_Q801_1
4_Q796_Page Submit
4_Q797_1
4_Q799_Page Submit
4_Q800_1
4_Q801_1
5_Q796_Page Submit
5_Q797_1
5_Q799_Page Submit
5_Q800_1
5_Q801_1
1_Q803_Page Submit
1_Q804_1
1_Q806_Page Submit
1_Q807_1
1_Q808_1
2_Q803_Page Submit
2_Q804_1
2_Q806_Page Submit
2_Q807_1
2_Q808_1
3_Q803_Page Submit
3_Q804_1
3_Q806_Page Submit
3_Q807_1
3_Q808_1
4_Q803_Page Submit
4_Q804_1
4_Q806_Page Submit
4_Q807_1
4_Q808_1
5_Q803_Page Submit
5_Q804_1
5_Q806_Page Submit
5_Q807_1
5_Q808_1
1_Q810_Page Submit
1_Q811_1
1_Q813_Page Submit
1_Q814_1
1_Q815_1
2_Q810_Page Submit
2_Q811_1
2_Q813_Page Submit
2_Q814_1
2_Q815_1
3_Q810_Page Submit
3_Q811_1
3_Q813_Page Submit
3_Q814_1
3_Q815_1
4_Q810_Page Submit
4_Q811_1
4_Q813_Page Submit
4_Q814_1
4_Q815_1
5_Q810_Page Submit
5_Q811_1
5_Q813_Page Submit
5_Q814_1
5_Q815_1
1_Q817_Page Submit
1_Q818_1
1_Q820_Page Submit
1_Q821_1
1_Q822_1
2_Q817_Page Submit
2_Q818_1
2_Q820_Page Submit
2_Q821_1
2_Q822_1
3_Q817_Page Submit
3_Q818_1
3_Q820_Page Submit
3_Q821_1
3_Q822_1
4_Q817_Page Submit
4_Q818_1
4_Q820_Page Submit
4_Q821_1
4_Q822_1
5_Q817_Page Submit
5_Q818_1
5_Q820_Page Submit
5_Q821_1
5_Q822_1
1_Q824_Page Submit
1_Q825_1
1_Q827_Page Submit
1_Q828_1
1_Q829_1
2_Q824_Page Submit
2_Q825_1
2_Q827_Page Submit
2_Q828_1
2_Q829_1
3_Q824_Page Submit
3_Q825_1
3_Q827_Page Submit
3_Q828_1
3_Q829_1
4_Q824_Page Submit
4_Q825_1
4_Q827_Page Submit
4_Q828_1
4_Q829_1
5_Q824_Page Submit
5_Q825_1
5_Q827_Page Submit
5_Q828_1
5_Q829_1
1_Q831_Page Submit
1_Q832_1
1_Q834_Page Submit
1_Q835_1
1_Q836_1
2_Q831_Page Submit
2_Q832_1
2_Q834_Page Submit
2_Q835_1
2_Q836_1
3_Q831_Page Submit
3_Q832_1
3_Q834_Page Submit
3_Q835_1
3_Q836_1
4_Q831_Page Submit
4_Q832_1
4_Q834_Page Submit
4_Q835_1
4_Q836_1
5_Q831_Page Submit
5_Q832_1
5_Q834_Page Submit
5_Q835_1
5_Q836_1
1_Q838_Page Submit
1_Q839_1
1_Q841_Page Submit
1_Q842_1
1_Q843_1
2_Q838_Page Submit
2_Q839_1
2_Q841_Page Submit
2_Q842_1
2_Q843_1
3_Q838_Page Submit
3_Q839_1
3_Q841_Page Submit
3_Q842_1
3_Q843_1
4_Q838_Page Submit
4_Q839_1
4_Q841_Page Submit
4_Q842_1
4_Q843_1
5_Q838_Page Submit
5_Q839_1
5_Q841_Page Submit
5_Q842_1
5_Q843_1
1_Q845_Page Submit
1_Q846_1
1_Q848_Page Submit
1_Q849_1
1_Q850_1
2_Q845_Page Submit
2_Q846_1
2_Q848_Page Submit
2_Q849_1
2_Q850_1
3_Q845_Page Submit
3_Q846_1
3_Q848_Page Submit
3_Q849_1
3_Q850_1
4_Q845_Page Submit
4_Q846_1
4_Q848_Page Submit
4_Q849_1
4_Q850_1
5_Q845_Page Submit
5_Q846_1
5_Q848_Page Submit
5_Q849_1
5_Q850_1
1_Q852_Page Submit
1_Q853_1
1_Q855_Page Submit
1_Q856_1
1_Q857_1
2_Q852_Page Submit
2_Q853_1
2_Q855_Page Submit
2_Q856_1
2_Q857_1
3_Q852_Page Submit
3_Q853_1
3_Q855_Page Submit
3_Q856_1
3_Q857_1
4_Q852_Page Submit
4_Q853_1
4_Q855_Page Submit
4_Q856_1
4_Q857_1
5_Q852_Page Submit
5_Q853_1
5_Q855_Page Submit
5_Q856_1
5_Q857_1
1_Q859_Page Submit
1_Q860_1
1_Q862_Page Submit
1_Q863_1
1_Q864_1
2_Q859_Page Submit
2_Q860_1
2_Q862_Page Submit
2_Q863_1
2_Q864_1
3_Q859_Page Submit
3_Q860_1
3_Q862_Page Submit
3_Q863_1
3_Q864_1
4_Q859_Page Submit
4_Q860_1
4_Q862_Page Submit
4_Q863_1
4_Q864_1
5_Q859_Page Submit
5_Q860_1
5_Q862_Page Submit
5_Q863_1
5_Q864_1
1_Q866_Page Submit
1_Q867_1
1_Q869_Page Submit
1_Q870_1
1_Q871_1
2_Q866_Page Submit
2_Q867_1
2_Q869_Page Submit
2_Q870_1
2_Q871_1
3_Q866_Page Submit
3_Q867_1
3_Q869_Page Submit
3_Q870_1
3_Q871_1
4_Q866_Page Submit
4_Q867_1
4_Q869_Page Submit
4_Q870_1
4_Q871_1
5_Q866_Page Submit
5_Q867_1
5_Q869_Page Submit
5_Q870_1
5_Q871_1
1_Q873_Page Submit
1_Q874_1
1_Q876_Page Submit
1_Q877_1
1_Q878_1
2_Q873_Page Submit
2_Q874_1
2_Q876_Page Submit
2_Q877_1
2_Q878_1
3_Q873_Page Submit
3_Q874_1
3_Q876_Page Submit
3_Q877_1
3_Q878_1
4_Q873_Page Submit
4_Q874_1
4_Q876_Page Submit
4_Q877_1
4_Q878_1
5_Q873_Page Submit
5_Q874_1
5_Q876_Page Submit
5_Q877_1
5_Q878_1
1_Q887_Page Submit
1_Q888_1
1_Q890_Page Submit
1_Q891_1
1_Q892_1
2_Q887_Page Submit
2_Q888_1
2_Q890_Page Submit
2_Q891_1
2_Q892_1
3_Q887_Page Submit
3_Q888_1
3_Q890_Page Submit
3_Q891_1
3_Q892_1
4_Q887_Page Submit
4_Q888_1
4_Q890_Page Submit
4_Q891_1
4_Q892_1
5_Q887_Page Submit
5_Q888_1
5_Q890_Page Submit
5_Q891_1
5_Q892_1
1_Q894_Page Submit
1_Q895_1
1_Q897_Page Submit
1_Q898_1
1_Q899_1
2_Q894_Page Submit
2_Q895_1
2_Q897_Page Submit
2_Q898_1
2_Q899_1
3_Q894_Page Submit
3_Q895_1
3_Q897_Page Submit
3_Q898_1
3_Q899_1
4_Q894_Page Submit
4_Q895_1
4_Q897_Page Submit
4_Q898_1
4_Q899_1
5_Q894_Page Submit
5_Q895_1
5_Q897_Page Submit
5_Q898_1
5_Q899_1
1_Q901_Page Submit
1_Q902_1
1_Q904_Page Submit
1_Q905_1
1_Q906_1
2_Q901_Page Submit
2_Q902_1
2_Q904_Page Submit
2_Q905_1
2_Q906_1
3_Q901_Page Submit
3_Q902_1
3_Q904_Page Submit
3_Q905_1
3_Q906_1
4_Q901_Page Submit
4_Q902_1
4_Q904_Page Submit
4_Q905_1
4_Q906_1
5_Q901_Page Submit
5_Q902_1
5_Q904_Page Submit
5_Q905_1
5_Q906_1
1_Q908_Page Submit
1_Q909_1
1_Q911_Page Submit
1_Q912_1
1_Q913_1
2_Q908_Page Submit
2_Q909_1
2_Q911_Page Submit
2_Q912_1
2_Q913_1
3_Q908_Page Submit
3_Q909_1
3_Q911_Page Submit
3_Q912_1
3_Q913_1
4_Q908_Page Submit
4_Q909_1
4_Q911_Page Submit
4_Q912_1
4_Q913_1
5_Q908_Page Submit
5_Q909_1
5_Q911_Page Submit
5_Q912_1
5_Q913_1
1_Q915_Page Submit
1_Q916_1
1_Q918_Page Submit
1_Q919_1
1_Q920_1
2_Q915_Page Submit
2_Q916_1
2_Q918_Page Submit
2_Q919_1
2_Q920_1
3_Q915_Page Submit
3_Q916_1
3_Q918_Page Submit
3_Q919_1
3_Q920_1
4_Q915_Page Submit
4_Q916_1
4_Q918_Page Submit
4_Q919_1
4_Q920_1
5_Q915_Page Submit
5_Q916_1
5_Q918_Page Submit
5_Q919_1
5_Q920_1
1_Q922_Page Submit
1_Q923_1
1_Q925_Page Submit
1_Q926_1
1_Q927_1
2_Q922_Page Submit
2_Q923_1
2_Q925_Page Submit
2_Q926_1
2_Q927_1
3_Q922_Page Submit
3_Q923_1
3_Q925_Page Submit
3_Q926_1
3_Q927_1
4_Q922_Page Submit
4_Q923_1
4_Q925_Page Submit
4_Q926_1
4_Q927_1
5_Q922_Page Submit
5_Q923_1
5_Q925_Page Submit
5_Q926_1
5_Q927_1
1_Q929_Page Submit
1_Q930_1
1_Q932_Page Submit
1_Q933_1
1_Q934_1
2_Q929_Page Submit
2_Q930_1
2_Q932_Page Submit
2_Q933_1
2_Q934_1
3_Q929_Page Submit
3_Q930_1
3_Q932_Page Submit
3_Q933_1
3_Q934_1
4_Q929_Page Submit
4_Q930_1
4_Q932_Page Submit
4_Q933_1
4_Q934_1
5_Q929_Page Submit
5_Q930_1
5_Q932_Page Submit
5_Q933_1
5_Q934_1
1_Q936_Page Submit
1_Q937_1
1_Q939_Page Submit
1_Q940_1
1_Q941_1
2_Q936_Page Submit
2_Q937_1
2_Q939_Page Submit
2_Q940_1
2_Q941_1
3_Q936_Page Submit
3_Q937_1
3_Q939_Page Submit
3_Q940_1
3_Q941_1
4_Q936_Page Submit
4_Q937_1
4_Q939_Page Submit
4_Q940_1
4_Q941_1
5_Q936_Page Submit
5_Q937_1
5_Q939_Page Submit
5_Q940_1
5_Q941_1
1_Q943_Page Submit
1_Q944_1
1_Q946_Page Submit
1_Q947_1
1_Q948_1
2_Q943_Page Submit
2_Q944_1
2_Q946_Page Submit
2_Q947_1
2_Q948_1
3_Q943_Page Submit
3_Q944_1
3_Q946_Page Submit
3_Q947_1
3_Q948_1
4_Q943_Page Submit
4_Q944_1
4_Q946_Page Submit
4_Q947_1
4_Q948_1
5_Q943_Page Submit
5_Q944_1
5_Q946_Page Submit
5_Q947_1
5_Q948_1
1_Q950_Page Submit
1_Q951_1
1_Q953_Page Submit
1_Q954_1
1_Q955_1
2_Q950_Page Submit
2_Q951_1
2_Q953_Page Submit
2_Q954_1
2_Q955_1
3_Q950_Page Submit
3_Q951_1
3_Q953_Page Submit
3_Q954_1
3_Q955_1
4_Q950_Page Submit
4_Q951_1
4_Q953_Page Submit
4_Q954_1
4_Q955_1
5_Q950_Page Submit
5_Q951_1
5_Q953_Page Submit
5_Q954_1
5_Q955_1
1_Q957_Page Submit
1_Q958_1
1_Q960_Page Submit
1_Q961_1
1_Q962_1
2_Q957_Page Submit
2_Q958_1
2_Q960_Page Submit
2_Q961_1
2_Q962_1
3_Q957_Page Submit
3_Q958_1
3_Q960_Page Submit
3_Q961_1
3_Q962_1
4_Q957_Page Submit
4_Q958_1
4_Q960_Page Submit
4_Q961_1
4_Q962_1
5_Q957_Page Submit
5_Q958_1
5_Q960_Page Submit
5_Q961_1
5_Q962_1
1_Q964_Page Submit
1_Q965_1
1_Q967_Page Submit
1_Q968_1
1_Q969_1
2_Q964_Page Submit
2_Q965_1
2_Q967_Page Submit
2_Q968_1
2_Q969_1
3_Q964_Page Submit
3_Q965_1
3_Q967_Page Submit
3_Q968_1
3_Q969_1
4_Q964_Page Submit
4_Q965_1
4_Q967_Page Submit
4_Q968_1
4_Q969_1
5_Q964_Page Submit
5_Q965_1
5_Q967_Page Submit
5_Q968_1
5_Q969_1
1_Q971_Page Submit
1_Q972_1
1_Q974_Page Submit
1_Q975_1
1_Q976_1
2_Q971_Page Submit
2_Q972_1
2_Q974_Page Submit
2_Q975_1
2_Q976_1
3_Q971_Page Submit
3_Q972_1
3_Q974_Page Submit
3_Q975_1
3_Q976_1
4_Q971_Page Submit
4_Q972_1
4_Q974_Page Submit
4_Q975_1
4_Q976_1
5_Q971_Page Submit
5_Q972_1
5_Q974_Page Submit
5_Q975_1
5_Q976_1
1_Q978_Page Submit
1_Q979_1
1_Q981_Page Submit
1_Q982_1
1_Q983_1
2_Q978_Page Submit
2_Q979_1
2_Q981_Page Submit
2_Q982_1
2_Q983_1
3_Q978_Page Submit
3_Q979_1
3_Q981_Page Submit
3_Q982_1
3_Q983_1
4_Q978_Page Submit
4_Q979_1
4_Q981_Page Submit
4_Q982_1
4_Q983_1
5_Q978_Page Submit
5_Q979_1
5_Q981_Page Submit
5_Q982_1
5_Q983_1
1_Q985_Page Submit
1_Q986_1
1_Q988_Page Submit
1_Q989_1
1_Q990_1
2_Q985_Page Submit
2_Q986_1
2_Q988_Page Submit
2_Q989_1
2_Q990_1
3_Q985_Page Submit
3_Q986_1
3_Q988_Page Submit
3_Q989_1
3_Q990_1
4_Q985_Page Submit
4_Q986_1
4_Q988_Page Submit
4_Q989_1
4_Q990_1
5_Q985_Page Submit
5_Q986_1
5_Q988_Page Submit
5_Q989_1
5_Q990_1
1_Q992_Page Submit
1_Q993_1
1_Q995_Page Submit
1_Q996_1
1_Q997_1
2_Q992_Page Submit
2_Q993_1
2_Q995_Page Submit
2_Q996_1
2_Q997_1
3_Q992_Page Submit
3_Q993_1
3_Q995_Page Submit
3_Q996_1
3_Q997_1
4_Q992_Page Submit
4_Q993_1
4_Q995_Page Submit
4_Q996_1
4_Q997_1
5_Q992_Page Submit
5_Q993_1
5_Q995_Page Submit
5_Q996_1
5_Q997_1
1_Q999_Page Submit
1_Q1000_1
1_Q1002_Page Submit
1_Q1003_1
1_Q1004_1
2_Q999_Page Submit
2_Q1000_1
2_Q1002_Page Submit
2_Q1003_1
2_Q1004_1
3_Q999_Page Submit
3_Q1000_1
3_Q1002_Page Submit
3_Q1003_1
3_Q1004_1
4_Q999_Page Submit
4_Q1000_1
4_Q1002_Page Submit
4_Q1003_1
4_Q1004_1
5_Q999_Page Submit
5_Q1000_1
5_Q1002_Page Submit
5_Q1003_1
5_Q1004_1
1_Q1006_Page Submit
1_Q1007_1
1_Q1009_Page Submit
1_Q1010_1
1_Q1011_1
2_Q1006_Page Submit
2_Q1007_1
2_Q1009_Page Submit
2_Q1010_1
2_Q1011_1
3_Q1006_Page Submit
3_Q1007_1
3_Q1009_Page Submit
3_Q1010_1
3_Q1011_1
4_Q1006_Page Submit
4_Q1007_1
4_Q1009_Page Submit
4_Q1010_1
4_Q1011_1
5_Q1006_Page Submit
5_Q1007_1
5_Q1009_Page Submit
5_Q1010_1
5_Q1011_1
1_Q1013_Page Submit
1_Q1014_1
1_Q1016_Page Submit
1_Q1017_1
1_Q1018_1
2_Q1013_Page Submit
2_Q1014_1
2_Q1016_Page Submit
2_Q1017_1
2_Q1018_1
3_Q1013_Page Submit
3_Q1014_1
3_Q1016_Page Submit
3_Q1017_1
3_Q1018_1
4_Q1013_Page Submit
4_Q1014_1
4_Q1016_Page Submit
4_Q1017_1
4_Q1018_1
5_Q1013_Page Submit
5_Q1014_1
5_Q1016_Page Submit
5_Q1017_1
5_Q1018_1
1_Q880_Page Submit
1_Q881_1
1_Q883_Page Submit
1_Q884_1
1_Q885_1
2_Q880_Page Submit
2_Q881_1
2_Q883_Page Submit
2_Q884_1
2_Q885_1
3_Q880_Page Submit
3_Q881_1
3_Q883_Page Submit
3_Q884_1
3_Q885_1
4_Q880_Page Submit
4_Q881_1
4_Q883_Page Submit
4_Q884_1
4_Q885_1
5_Q880_Page Submit
5_Q881_1
5_Q883_Page Submit
5_Q884_1
5_Q885_1
1_Q1020_Page Submit
1_Q1021_1
1_Q1023_Page Submit
1_Q1024_1
1_Q1025_1
2_Q1020_Page Submit
2_Q1021_1
2_Q1023_Page Submit
2_Q1024_1
2_Q1025_1
3_Q1020_Page Submit
3_Q1021_1
3_Q1023_Page Submit
3_Q1024_1
3_Q1025_1
4_Q1020_Page Submit
4_Q1021_1
4_Q1023_Page Submit
4_Q1024_1
4_Q1025_1
5_Q1020_Page Submit
5_Q1021_1
5_Q1023_Page Submit
5_Q1024_1
5_Q1025_1
1_Q1027_Page Submit
1_Q1028_1
1_Q1030_Page Submit
1_Q1031_1
1_Q1032_1
2_Q1027_Page Submit
2_Q1028_1
2_Q1030_Page Submit
2_Q1031_1
2_Q1032_1
3_Q1027_Page Submit
3_Q1028_1
3_Q1030_Page Submit
3_Q1031_1
3_Q1032_1
4_Q1027_Page Submit
4_Q1028_1
4_Q1030_Page Submit
4_Q1031_1
4_Q1032_1
5_Q1027_Page Submit
5_Q1028_1
5_Q1030_Page Submit
5_Q1031_1
5_Q1032_1
1_Q1034_Page Submit
1_Q1035_1
1_Q1037_Page Submit
1_Q1038_1
1_Q1039_1
2_Q1034_Page Submit
2_Q1035_1
2_Q1037_Page Submit
2_Q1038_1
2_Q1039_1
3_Q1034_Page Submit
3_Q1035_1
3_Q1037_Page Submit
3_Q1038_1
3_Q1039_1
4_Q1034_Page Submit
4_Q1035_1
4_Q1037_Page Submit
4_Q1038_1
4_Q1039_1
5_Q1034_Page Submit
5_Q1035_1
5_Q1037_Page Submit
5_Q1038_1
5_Q1039_1
1_Q1041_Page Submit
1_Q1042_1
1_Q1044_Page Submit
1_Q1045_1
1_Q1046_1
2_Q1041_Page Submit
2_Q1042_1
2_Q1044_Page Submit
2_Q1045_1
2_Q1046_1
3_Q1041_Page Submit
3_Q1042_1
3_Q1044_Page Submit
3_Q1045_1
3_Q1046_1
4_Q1041_Page Submit
4_Q1042_1
4_Q1044_Page Submit
4_Q1045_1
4_Q1046_1
5_Q1041_Page Submit
5_Q1042_1
5_Q1044_Page Submit
5_Q1045_1
5_Q1046_1
1_Q1048_Page Submit
1_Q1049_1
1_Q1051_Page Submit
1_Q1052_1
1_Q1053_1
2_Q1048_Page Submit
2_Q1049_1
2_Q1051_Page Submit
2_Q1052_1
2_Q1053_1
3_Q1048_Page Submit
3_Q1049_1
3_Q1051_Page Submit
3_Q1052_1
3_Q1053_1
4_Q1048_Page Submit
4_Q1049_1
4_Q1051_Page Submit
4_Q1052_1
4_Q1053_1
5_Q1048_Page Submit
5_Q1049_1
5_Q1051_Page Submit
5_Q1052_1
5_Q1053_1
1_Q1055_Page Submit
1_Q1056_1
1_Q1058_Page Submit
1_Q1059_1
1_Q1060_1
2_Q1055_Page Submit
2_Q1056_1
2_Q1058_Page Submit
2_Q1059_1
2_Q1060_1
3_Q1055_Page Submit
3_Q1056_1
3_Q1058_Page Submit
3_Q1059_1
3_Q1060_1
4_Q1055_Page Submit
4_Q1056_1
4_Q1058_Page Submit
4_Q1059_1
4_Q1060_1
5_Q1055_Page Submit
5_Q1056_1
5_Q1058_Page Submit
5_Q1059_1
5_Q1060_1
1_Q1062_Page Submit
1_Q1063_1
1_Q1065_Page Submit
1_Q1066_1
1_Q1067_1
2_Q1062_Page Submit
2_Q1063_1
2_Q1065_Page Submit
2_Q1066_1
2_Q1067_1
3_Q1062_Page Submit
3_Q1063_1
3_Q1065_Page Submit
3_Q1066_1
3_Q1067_1
4_Q1062_Page Submit
4_Q1063_1
4_Q1065_Page Submit
4_Q1066_1
4_Q1067_1
5_Q1062_Page Submit
5_Q1063_1
5_Q1065_Page Submit
5_Q1066_1
5_Q1067_1
1_Q1069_Page Submit
1_Q1070_1
1_Q1072_Page Submit
1_Q1073_1
1_Q1074_1
2_Q1069_Page Submit
2_Q1070_1
2_Q1072_Page Submit
2_Q1073_1
2_Q1074_1
3_Q1069_Page Submit
3_Q1070_1
3_Q1072_Page Submit
3_Q1073_1
3_Q1074_1
4_Q1069_Page Submit
4_Q1070_1
4_Q1072_Page Submit
4_Q1073_1
4_Q1074_1
5_Q1069_Page Submit
5_Q1070_1
5_Q1072_Page Submit
5_Q1073_1
5_Q1074_1
1_Q1076_Page Submit
1_Q1077_1
1_Q1079_Page Submit
1_Q1080_1
1_Q1081_1
2_Q1076_Page Submit
2_Q1077_1
2_Q1079_Page Submit
2_Q1080_1
2_Q1081_1
3_Q1076_Page Submit
3_Q1077_1
3_Q1079_Page Submit
3_Q1080_1
3_Q1081_1
4_Q1076_Page Submit
4_Q1077_1
4_Q1079_Page Submit
4_Q1080_1
4_Q1081_1
5_Q1076_Page Submit
5_Q1077_1
5_Q1079_Page Submit
5_Q1080_1
5_Q1081_1
1_Q1083_Page Submit
1_Q1084_1
1_Q1086_Page Submit
1_Q1087_1
1_Q1088_1
2_Q1083_Page Submit
2_Q1084_1
2_Q1086_Page Submit
2_Q1087_1
2_Q1088_1
3_Q1083_Page Submit
3_Q1084_1
3_Q1086_Page Submit
3_Q1087_1
3_Q1088_1
4_Q1083_Page Submit
4_Q1084_1
4_Q1086_Page Submit
4_Q1087_1
4_Q1088_1
5_Q1083_Page Submit
5_Q1084_1
5_Q1086_Page Submit
5_Q1087_1
5_Q1088_1
1_Q1090_Page Submit
1_Q1091_1
1_Q1093_Page Submit
1_Q1094_1
1_Q1095_1
2_Q1090_Page Submit
2_Q1091_1
2_Q1093_Page Submit
2_Q1094_1
2_Q1095_1
3_Q1090_Page Submit
3_Q1091_1
3_Q1093_Page Submit
3_Q1094_1
3_Q1095_1
4_Q1090_Page Submit
4_Q1091_1
4_Q1093_Page Submit
4_Q1094_1
4_Q1095_1
5_Q1090_Page Submit
5_Q1091_1
5_Q1093_Page Submit
5_Q1094_1
5_Q1095_1
1_Q1097_Page Submit
1_Q1098_1
1_Q1100_Page Submit
1_Q1101_1
1_Q1102_1
2_Q1097_Page Submit
2_Q1098_1
2_Q1100_Page Submit
2_Q1101_1
2_Q1102_1
3_Q1097_Page Submit
3_Q1098_1
3_Q1100_Page Submit
3_Q1101_1
3_Q1102_1
4_Q1097_Page Submit
4_Q1098_1
4_Q1100_Page Submit
4_Q1101_1
4_Q1102_1
5_Q1097_Page Submit
5_Q1098_1
5_Q1100_Page Submit
5_Q1101_1
5_Q1102_1
1_Q1104_Page Submit
1_Q1105_1
1_Q1107_Page Submit
1_Q1108_1
1_Q1109_1
2_Q1104_Page Submit
2_Q1105_1
2_Q1107_Page Submit
2_Q1108_1
2_Q1109_1
3_Q1104_Page Submit
3_Q1105_1
3_Q1107_Page Submit
3_Q1108_1
3_Q1109_1
4_Q1104_Page Submit
4_Q1105_1
4_Q1107_Page Submit
4_Q1108_1
4_Q1109_1
5_Q1104_Page Submit
5_Q1105_1
5_Q1107_Page Submit
5_Q1108_1
5_Q1109_1
1_Q1111_Page Submit
1_Q1112_1
1_Q1114_Page Submit
1_Q1115_1
1_Q1116_1
2_Q1111_Page Submit
2_Q1112_1
2_Q1114_Page Submit
2_Q1115_1
2_Q1116_1
3_Q1111_Page Submit
3_Q1112_1
3_Q1114_Page Submit
3_Q1115_1
3_Q1116_1
4_Q1111_Page Submit
4_Q1112_1
4_Q1114_Page Submit
4_Q1115_1
4_Q1116_1
5_Q1111_Page Submit
5_Q1112_1
5_Q1114_Page Submit
5_Q1115_1
5_Q1116_1
1_Q1118_Page Submit
1_Q1119_1
1_Q1121_Page Submit
1_Q1122_1
1_Q1123_1
2_Q1118_Page Submit
2_Q1119_1
2_Q1121_Page Submit
2_Q1122_1
2_Q1123_1
3_Q1118_Page Submit
3_Q1119_1
3_Q1121_Page Submit
3_Q1122_1
3_Q1123_1
4_Q1118_Page Submit
4_Q1119_1
4_Q1121_Page Submit
4_Q1122_1
4_Q1123_1
5_Q1118_Page Submit
5_Q1119_1
5_Q1121_Page Submit
5_Q1122_1
5_Q1123_1
1_Q1125_Page Submit
1_Q1126_1
1_Q1128_Page Submit
1_Q1129_1
1_Q1130_1
2_Q1125_Page Submit
2_Q1126_1
2_Q1128_Page Submit
2_Q1129_1
2_Q1130_1
3_Q1125_Page Submit
3_Q1126_1
3_Q1128_Page Submit
3_Q1129_1
3_Q1130_1
4_Q1125_Page Submit
4_Q1126_1
4_Q1128_Page Submit
4_Q1129_1
4_Q1130_1
5_Q1125_Page Submit
5_Q1126_1
5_Q1128_Page Submit
5_Q1129_1
5_Q1130_1
1_Q1132_Page Submit
1_Q1133_1
1_Q1135_Page Submit
1_Q1136_1
1_Q1137_1
2_Q1132_Page Submit
2_Q1133_1
2_Q1135_Page Submit
2_Q1136_1
2_Q1137_1
3_Q1132_Page Submit
3_Q1133_1
3_Q1135_Page Submit
3_Q1136_1
3_Q1137_1
4_Q1132_Page Submit
4_Q1133_1
4_Q1135_Page Submit
4_Q1136_1
4_Q1137_1
5_Q1132_Page Submit
5_Q1133_1
5_Q1135_Page Submit
5_Q1136_1
5_Q1137_1
1_Q1139_Page Submit
1_Q1140_1
1_Q1142_Page Submit
1_Q1143_1
1_Q1144_1
2_Q1139_Page Submit
2_Q1140_1
2_Q1142_Page Submit
2_Q1143_1
2_Q1144_1
3_Q1139_Page Submit
3_Q1140_1
3_Q1142_Page Submit
3_Q1143_1
3_Q1144_1
4_Q1139_Page Submit
4_Q1140_1
4_Q1142_Page Submit
4_Q1143_1
4_Q1144_1
5_Q1139_Page Submit
5_Q1140_1
5_Q1142_Page Submit
5_Q1143_1
5_Q1144_1
1_Q1146_Page Submit
1_Q1147_1
1_Q1149_Page Submit
1_Q1150_1
1_Q1151_1
2_Q1146_Page Submit
2_Q1147_1
2_Q1149_Page Submit
2_Q1150_1
2_Q1151_1
3_Q1146_Page Submit
3_Q1147_1
3_Q1149_Page Submit
3_Q1150_1
3_Q1151_1
4_Q1146_Page Submit
4_Q1147_1
4_Q1149_Page Submit
4_Q1150_1
4_Q1151_1
5_Q1146_Page Submit

In [8]:
df.shape

(88, 946)

In [9]:
n_frame_blocks = 20
affect_per_frame = 5
affect_trial_size = 3

start_candidates = [1, 341, 641]

records = []

for row_idx in range(len(df)):

    row = df.iloc[row_idx]

    # ==========================================
    # ① Affectの開始位置を決定
    # ==========================================

    if pd.notna(row.iloc[1]):
        start_col = 1
        condition = 1

    elif pd.notna(row.iloc[341]):
        start_col = 341
        condition = 2

    elif pd.notna(row.iloc[641]):
        start_col = 641
        condition = 3

    else:
        raise ValueError(
            f"CellNotFound: row={row_idx}, "
            f"columns={start_candidates}"
        )

    # ==========================================
    # ② Frame Choiceを最初の領域から探索
    # ==========================================

    frame_values = []

    # Frame Choiceはconditionに関係なく
    # 1列目から探索
    for col_idx in range(1, len(row)):

        value = row.iloc[col_idx]

        if "半分" in str(value):

            frame_values.append([
                row.iloc[col_idx - 1],
                value
            ])

            if len(frame_values) == n_frame_blocks:
                break

    # ==========================================
    # Frame数を確認
    # ==========================================

    if len(frame_values) != n_frame_blocks:
        raise ValueError(
            f"Frame Choice不足: "
            f"row={row_idx}, "
            f"condition={condition}, "
            f"取得数={len(frame_values)}"
        )

    # ==========================================
    # ③ Frame 20ブロック
    # ==========================================

    for i in range(n_frame_blocks):

        frame_vals = frame_values[i]

        # ======================================
        # ④ 1 FrameにつきAffect 5試行
        # ======================================

        for j in range(affect_per_frame):

            affect_idx = i * affect_per_frame + j

            # ----------------------------------
            # Affectの開始列
            # ----------------------------------

            if condition == 1:

                # 15列(Affect) + 2列(Frame)
                affect_start = (
                    start_col
                    + i * 17
                    + j * 3
                )

            else:

                # 条件2・3
                affect_start = (
                    start_col
                    + affect_idx * 3
                )

            # ----------------------------------
            # Affect 3列
            # ----------------------------------

            affect_vals = row.iloc[
                affect_start:affect_start + affect_trial_size
            ].values

            # ----------------------------------
            # 1レコード
            # ----------------------------------

            record = {
                "responseId": row.iloc[0],

                "frame_block": i,
                "affect_trial": j,

                "Page Submit_al": affect_vals[0],
                "Alertness Level": affect_vals[1],
                "Affect Level": affect_vals[2],

                "frame_1": frame_vals[0],
                "frame_2": frame_vals[1],

                "Message Group": row["__js_MessageGroup"]
            }

            records.append(record)


new_df = pd.DataFrame(records)

print("Shape:", new_df.shape)

Shape: (8800, 9)

In [10]:
print(new_df.columns)

Index(['responseId', 'frame_block', 'affect_trial', 'Page Submit_al',
       'Alertness Level', 'Affect Level', 'frame_1', 'frame_2',
       'Message Group'],
      dtype='str')

In [11]:
new_df["frame_2"] = new_df["frame_2"].map({
    "半分も入っている": 0,
    "半分しか入っていない": 1
})

In [12]:
new_df = new_df.rename(columns={
    "affect_trial":"ref_subblock",
    "frame_1":"Page Submit_fc",
    "frame_2":"frame_choice"
})

In [13]:
new_df.shape

(8800, 9)

In [14]:
new_df

,responseId,frame_block,ref_subblock,Page Submit_al,Alertness Level,Affect Level,Page Submit_fc,frame_choice,Message Group
0,R_9nvFNaU5rMNP8Vi,0,0,5.553,28.0,39.0,8.803,1,neutral
1,R_9nvFNaU5rMNP8Vi,0,1,13.783,45.0,39.0,8.803,1,neutral
2,R_9nvFNaU5rMNP8Vi,0,2,4.873,38.0,49.0,8.803,1,neutral
3,R_9nvFNaU5rMNP8Vi,0,3,14.086,82.0,17.0,8.803,1,neutral
4,R_9nvFNaU5rMNP8Vi,0,4,13.431,60.0,48.0,8.803,1,neutral
...,...,...,...,...,...,...,...,...,...
8795,R_48fjCyEBqTZJTy1,19,0,12.925,70.0,10.0,4.637,0,negative
8796,R_48fjCyEBqTZJTy1,19,1,11.287,90.0,5.0,4.637,0,negative
8797,R_48fjCyEBqTZJTy1,19,2,30.534,20.0,40.0,4.637,0,negative
8798,R_48fjCyEBqTZJTy1,19,3,11.116,25.0,30.0,4.637,0,negative
8799,R_48fjCyEBqTZJTy1,19,4,18.222,50.0,45.0,4.637,0,negative

In [15]:
new_df.to_csv("../data/formatted_trial_exp1.csv",index=False)